title = "Pan Feng的博客" # 博客的名字
# 主题
theme = "maupassant"

# 
baseURL = "http://www.github.com"

# 语言
languageCode = "zh-CN"

# 谷歌GA分析统计
googleAnalytics = "GA ID"


[author]
  name = "Pan Feng"

[params]
  author = "Pan Feng 的博客"
  subtitle = "初来乍到，请多指教"
  keywords = "阿斯蒂芬"
  description = "22222"


  # 自定义菜单 ，右上角

[menu]
#   [[menu.main]]
#     identifier = "books"
#     name = "新书"
#     url = "/books/"
#     weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4


# 友情链接
[[params.links]]
    name = "theme来源:飞雪无情的博客"
    title = "飞雪无情的博客"
    url = "https://github.com/rujews/maupassant-hugo"
[[params.links]]
  title = "Android Gradle权威指南"
  name = "Android Gradle权威指南"
  url = "http://yuedu.baidu.com/ebook/14a722970740be1e640e9a3e"
[[params.links]]
  title = "常用开发工具CDN镜像"
  name = "常用开发工具CDN镜像"
  url = "http://mirrors.flysnow.org/"

# 一些组件

# disqus 评论
disqusShortname = "yourdiscussshortname"

# utteranc 评论
[params.utteranc]
    enable = true
    repo = ""    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true

## 是否禁止URL Path转小写
disablePathToLower = true